### ISSUE TITLE
Support for python

### ISSUE THREAD

**Issue by vikigenius** [jackkamm/ob-session-async#4]
I know python already has jupyter. But it would be useful to have support for python anyway.

**Comment by jackkamm** [comment]
I've added partial support for Python (`:results output` only) in 0b826d4.

I haven't implemented `:results value`, because ob-python's implementation of `:session :results value` is very fragile and buggy. I'd like to see if the situation can be improved upstream before attempting an async version. In the meantime, I'll leave this issue open.

**Comment by jackkamm** [comment]
I pushed some fixes upstream for ob-python `:session :results value`:
https://lists.gnu.org/archive/html/emacs-orgmode/2020-01/msg00190.html
https://lists.gnu.org/archive/html/emacs-orgmode/2020-02/msg00119.html
They will be released in Org 9.4, which should be coming out soon. At that point, I'll merge my PR for the async implementation (https://github.com/jackkamm/ob-session-async/pull/6) which depends on these fixes.
